export interface Vehicle {
  slug: string;
  brand: "Lamborghini" | "Ferrari" | "Bentley" | "Rolls-Royce" | "McLaren" | "Mercedes-AMG";
  model: string;
  variant: string;
  year: number;
  km: number;
  power: number;
  fuel: "Gasolina" | "Híbrido enchufable";
  transmission: "Automática" | "Manual";
  emissions: number;
  originPrice: number;
  location: string;
  image?: string;
  status?: "borrador" | "transito" | "disponible";
  notes?: string;
}

export const vehicles: Vehicle[] = [
  {
    slug: "lamborghini-huracan-evo-2021",
    brand: "Lamborghini",
    model: "Huracán",
    variant: "EVO RWD",
    year: 2021,
    km: 8500,
    power: 640,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 331,
    originPrice: 185000,
    location: "Dubái, EAU",
    image: "/vehicles/lamborghini-huracan-evo-2021.jpg",
    status: "disponible",
  },
  {
    slug: "lamborghini-urus-s-2022",
    brand: "Lamborghini",
    model: "Urus",
    variant: "S",
    year: 2022,
    km: 15000,
    power: 650,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 325,
    originPrice: 165000,
    location: "Dubái, EAU",
    image: "/vehicles/lamborghini-urus-s-2022.jpg",
    status: "disponible",
  },
  {
    slug: "ferrari-488-gtb-2020",
    brand: "Ferrari",
    model: "488",
    variant: "GTB",
    year: 2020,
    km: 12000,
    power: 670,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 260,
    originPrice: 195000,
    location: "Dubái, EAU",
    image: "/vehicles/ferrari-488-gtb-2020.jpg",
    status: "disponible",
  },
  {
    slug: "ferrari-sf90-stradale-2022",
    brand: "Ferrari",
    model: "SF90",
    variant: "Stradale Assetto Fiorano",
    year: 2022,
    km: 4200,
    power: 1000,
    fuel: "Híbrido enchufable",
    transmission: "Automática",
    emissions: 154,
    originPrice: 385000,
    location: "Dubái, EAU",
    image: "/vehicles/ferrari-sf90-stradale-2022.jpg",
    status: "transito",
  },
  {
    slug: "bentley-continental-gt-2021",
    brand: "Bentley",
    model: "Continental GT",
    variant: "V8 Mulliner",
    year: 2021,
    km: 18000,
    power: 550,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 275,
    originPrice: 175000,
    location: "Dubái, EAU",
    image: "/vehicles/bentley-continental-gt-2021.jpg",
    status: "disponible",
  },
  {
    slug: "bentley-bentayga-v8-2020",
    brand: "Bentley",
    model: "Bentayga",
    variant: "V8",
    year: 2020,
    km: 32000,
    power: 550,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 292,
    originPrice: 145000,
    location: "Abu Dabi, EAU",
    image: "/vehicles/bentley-bentayga-v8-2020.jpg",
    status: "disponible",
  },
  {
    slug: "rolls-royce-cullinan-black-badge-2021",
    brand: "Rolls-Royce",
    model: "Cullinan",
    variant: "Black Badge",
    year: 2021,
    km: 21000,
    power: 571,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 341,
    originPrice: 295000,
    location: "Dubái, EAU",
    image: "/vehicles/rolls-royce-cullinan-black-badge-2021.jpg",
    status: "disponible",
  },
  {
    slug: "rolls-royce-ghost-extended-2022",
    brand: "Rolls-Royce",
    model: "Ghost",
    variant: "Extended",
    year: 2022,
    km: 9800,
    power: 563,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 359,
    originPrice: 320000,
    location: "Dubái, EAU",
    image: "/vehicles/rolls-royce-ghost-extended-2022.jpg",
    status: "transito",
  },
  {
    slug: "mclaren-720s-performance-2019",
    brand: "McLaren",
    model: "720S",
    variant: "Performance",
    year: 2019,
    km: 14500,
    power: 720,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 249,
    originPrice: 210000,
    location: "Dubái, EAU",
    image: "/vehicles/mclaren-720s-performance-2019.jpg",
    status: "disponible",
  },
  {
    slug: "mercedes-amg-g63-edition1-2022",
    brand: "Mercedes-AMG",
    model: "G 63",
    variant: "Edition 1",
    year: 2022,
    km: 11000,
    power: 585,
    fuel: "Gasolina",
    transmission: "Automática",
    emissions: 296,
    originPrice: 168000,
    location: "Abu Dabi, EAU",
    image: "/vehicles/mercedes-amg-g63-edition1-2022.jpg",
    status: "disponible",
  },
];
